[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eark-ip-validation"
dynamic = ["version"]
authors = [
  { name="Carl Wilson", email="carl@openpreservation.org" },
  { name="Darren Dignam", email="darren@openpreservation.org" },
]
maintainers = [
  { name="Carl Wilson", email="carl@openpreservation.org" },
  { name="Darren Dignam", email="carl@openpreservation.org" },
]
license = {file = "LICENSE"}
description = "E-ARK Python Information Package validation library."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]
dependencies = [
    "lxml",
    "importlib_resources",
]